### ISSUE TITLE
How to find CORE, MMLU, EXTENDED values in the eval json?

### ISSUE THREAD

**Issue by pavel-denisov-fraunhofer** [mlfoundations/dclm#10]
Hi, thanks a lot for this work!

I trained a small LM on my data and run evaluation with json output. How can I find numbers corresponding to the CORE, MMLU, EXTENDED values in the table?

**Comment by Vaishaal** [comment]
Hi!
Core is actually just  "low_variance_centered"
Extended is ""aggregated_centered_results"


The task list can be found here: https://github.com/mlfoundations/dclm/blob/main/eval/additional_aggregation.json 
"low_variance" is "core"

**Comment by Vaishaal** [comment]
if you post your json I can help you find it, so sorry about the confusing naming!
