### ISSUE TITLE
Could you please release the 8.2B token for the 400M-1x setting?

### ISSUE THREAD

**Issue by xszheng2020** [mlfoundations/dclm#100]
Hi, @afang-story 

Could you please release the 8.2B token for the [400M-1x](https://huggingface.co/datasets/mlfoundations/dclm-pool-400m-1x) setting?

**Comment by GeorgiosSmyrnis** [comment]
Hi @xszheng2020 ,

To train with the subset of DCLM-baseline at this scale, I would recommend one of the following depending on what you want to use it for (participate or simply train a model using the data at this scale):
- Running the processing pipeline on top of the 400m-1x pool here: https://huggingface.co/datasets/mlfoundations/dclm-pool-400m-1x.
- Subsampling the desired number of tokens from the full DCLM-baseline dataset.
- If you want to experiment on just the final stage (filtering method after RefinedWeb processing), you can download one of the local shards of DCLM-RefinedWeb here: https://data.commoncrawl.org/contrib/datacomp/DCLM-refinedweb/index.html - it will provide you with enough tokens to apply the final filtering at this scale.
