### ISSUE TITLE
Would you share the 0.28T token dataset for achieve highest scores in 7B-2x experiment?

### ISSUE THREAD

**Issue by xinghuang2050** [mlfoundations/dclm#21]
Fantastic work!

I am highly impressed by this project. It is remarkable that a 7B model achieved a score of 50.8 on MMLU after being trained on just a 0.28T token dataset. Would it be possible for you to share this crucial part of the dataset?

Thank you very much for your hard work and contributions.

**Comment by Mivg** [comment]
Hi @xinghuang2050 
Thank you for your kind words. 
The 7B model you mentioned was trained on the a random subset from the full DCLM-Baseline pool which is available from https://huggingface.co/datasets/mlfoundations/dclm-baseline-1.0
