### ISSUE TITLE
Missing scale configs?

### ISSUE THREAD

**Issue by ch-shin** [mlfoundations/dclm#27]
Hi, team!

I am trying to run the training code, but it seems scale config files are missing. (https://github.com/mlfoundations/dclm/blob/fbb24afbc66abed64b5fefc16f12f3511138f05e/training/hyperparameters.py#L81)
Are these config files going to be uploaded later, or do we have to write it ourselves?

**Comment by jeffreywpli** [comment]
sorry about that! we just merged the configs used for the competition scales.
