### ISSUE TITLE
How to train and fine-tuning model

### ISSUE THREAD

**Issue by Jackjiayou** [mlfoundations/dclm#34]
Hello, may I ask how to train a fine-tuning model, such as Lora fine-tuning. Which chapter has an introduction。
Thanks

**Comment by Mivg** [comment]
Hi @Jackjiayou ,
Can you please clarify your question? Are you asking about instruction fine-tuning, or general fine-tuning of the pretrained DCLM checkpoints? If the latter is correct, you can load it as any HuggingFace model and fine-tune through the HF recipes.
