### ISSUE TITLE
Question regarding the evaluation

### ISSUE THREAD

**Issue by SivilTaram** [mlfoundations/dclm#4]
Thanks for your awesome work! I'd like to follow your work and evaluate our models. I have a quick question regarding the evaluation - which specific evaluation config file is related to the "Core" set mentioned in your paper?

Thanks,
Qian

**Comment by Hritikbansal** [comment]
Hi @SivilTaram , thanks for your interest in our work.

This is the config file for CORE evals (including MMLU): https://github.com/mlfoundations/dclm/blob/main/eval/mmlu_and_lowvar.yaml

**Comment by LefanZhang** [comment]
Hi @Hritikbansal , thanks for your great job.

I want to know which config file should I use for Extended evals? I tried [mmlu_and_lowvar.yaml](https://github.com/mlfoundations/dclm/blob/main/eval/mmlu_and_lowvar.yaml), but the result was not aligned with leaderboard.
