### ISSUE TITLE
Missing FastText Config File

### ISSUE THREAD

**Issue by purefall** [mlfoundations/dclm#40]
Hi all, 

While following your [README.md](https://github.com/mlfoundations/dclm/tree/main/baselines#readme) under "SampleWorkflows/Fasttext Filtering" you refer to a missing yaml file with the following link: 

https://github.com/mlfoundations/dclm/blob/main/baselines/baselines_configs/fasttext_filter.yaml

Are you planning to add this yaml to the repo?

**Comment by jeffreywpli** [comment]
sorry about that, it should now be there!
