### ISSUE TITLE
Missing training model configs 

### ISSUE THREAD

**Issue by ch-shin** [mlfoundations/dclm#41]
Hi team, thank you for the great work!

https://github.com/mlfoundations/dclm/blob/c0b0f6cf49c4344fb6f7f6248bd569f072eb036b/training/configs/411m_1x.json#L2 
It seems `training/open_lm_configs/d=1024_l=24_h=8.json` should be there, but missing currently.

**Comment by afang-story** [comment]
Thanks for catching this issue. I believe this is now resolved with this commit https://github.com/mlfoundations/dclm/commit/ab4ef62815215531f2580ebf5e70c2f5e51c51d8
