### ISSUE TITLE
What is the pearson correlation in lighteval scores between 1B/400M model and 7B model?

### ISSUE THREAD

**Issue by ZefanW** [mlfoundations/dclm#46]
Really appreciate your work! 
I am wondering if you could share the Pearson correlation for core/mmlu/extended scores between the 7B and smaller models ( similar to the statistics presented in Section 3.2 ) using the LightEval package. 
According to your experiment in Appendix G.2 and in recent literature [1], metrics based on the entire answer's log probability tend to show lower variance and steeper changes in pre-training ablations when the training token amount is relatively small. 
This has drawn my curiosity about whether using other evaluation methods that incorporate entire answer log probability, instead of llm-foundry, might offer more scientifically solid results for a leaderboard. 
I would be extremely grateful if you could provide any insights or data on this topic. 

[1] Madaan, Lovish, et al. "Quantifying Variance in Evaluation Benchmarks." arXiv preprint arXiv:2406.10229 (2024).

**Comment by afang-story** [comment]
Unfortunately we currently do not have the bandwidth to run LightEval on our models. I agree that reducing evaluation variance is an important research direction and would suggest you look into other work that has used perplexity evaluation, such as https://arxiv.org/abs/2403.08540
