### ISSUE TITLE
Example command using ray_processing/process.py

### ISSUE THREAD

**Issue by tonychenxyz** [mlfoundations/dclm#47]
Hi! I was wondering if a sample command using ray_processing/process.py can provided.

The readme has `python3 ray_processing/process.py --source_ref_paths <source_json> --readable_name <name> --output_dir <s3_output_dir> --config_path <config_yaml> --source_name <source_name>`

But I'm unsure what files each argument corresponds to. A sample command with corresponding example files could be helpful.

Thanks

**Comment by tonychenxyz** [comment]
Thanks for the reference. What should the structure of raw_data_dirpath be?
Should it be a directory containing jsonl files?

**Comment by afang-story** [comment]
Yes.

Also to be clear, the above examples do not use that argument and instead use a source such as "exp_data/datasets/raw_sources/CC_WET_april_2019.json"
You can create your own modeled off of this https://github.com/mlfoundations/dclm/blob/main/exp_data/datasets/raw_sources/CC_WET_april_2019.json and specify the dataset_url

**Comment by tonychenxyz** [comment]
Thanks! It seems like the readme page [here](https://github.com/mlfoundations/dclm/blob/ab4ef62815215531f2580ebf5e70c2f5e51c51d8/baselines/README.md?plain=1#L86) doesn't have example for all arguments. 

e.g. `shard_list_file` seems to be needed for running processing locally. What should it point to? The only documentation I can find is “Path to a file containing a list of input shards.”  But it isn't very clear what exactly the files should look like.

Thanks.
