### ISSUE TITLE
Training variance

### ISSUE THREAD

**Issue by ttccxx** [mlfoundations/dclm#48]
Hi, thanks for your great work!

I was trying to reproduce the DCLM-400M-1x model, but seemed to get results different from the leaderboard. Specifically, the MMLU score is 0.234, and the core set score is 0.210, which I think have large differences with the leaderboard (MMLU 0.255, core set 0.180).

So I wonder how's variance between different runs? Especially when the data is sampled randomly from the pool (if I understand correctly), will there be large fluctuations?

And I also encountered many eval datasets to have zero scores, like some bigbench datasets. Is that a normal phenomenon? Thanks for your time in advance!

**Comment by afang-story** [comment]
@ttccxx while MMLU differences are expected at this scale, the difference in core seems higher than expected. Could you clarify what dataset you train on and how you subsample?

**Comment by ttccxx** [comment]
Thanks for your reply. I found that I made some mistakes in both training and evaluation. After fixing them, I got MMLU 25.3 and Core 16.5. Is that a reasonable score?

As for training data, I sample from global-shard_05/06/07/08_of_10 of dclm-baseline-1.0 (other shards' preprocessing is not finished, but the amount should be enough I suppose). Other parameters are the same as the config.

There is another small problem that I don't know whether is related to this problem: I saw that in args passed to open_lm, "epoch" is set to 5. But at the second epoch, I got the message that the training was finished. Is this normal behavior?

I greatly appreciate your help!

![image](https://github.com/user-attachments/assets/95c1fdcc-8b18-4cea-984c-4f6fbe8cd3e1)

**Comment by afang-story** [comment]
0.165 seems a bit low. However, dclm baseline 1.0 is also slightly different than starting with https://huggingface.co/datasets/mlfoundations/dclm-pool-400m-1x or one of the other pools and running refinedweb and fasttext filtering (such as input shards, choice of deduplication), though I am not sure if this and variance capture the entire difference.

Regarding checkpoints, when you set epoch to 5, we make a best effort to do 5 epochs but sometimes this isn't possible. You should scroll up in your logs and you will probably find a message that adjusted the number of checkpoints to 2. This does seem to be the right number of steps though.

**Comment by ttccxx** [comment]
Thanks for your reply. I'm more clear now.

BTW, just to be sure, if I train a DCLM-7B-1x model on dclm-baseline-1.0, I will get results close to that in Table 9 in the paper, and this is different from the DCLM-7B-1x results on the leaderboard. Is that correct?

**Comment by afang-story** [comment]
Correct. I believe Table 9 results actually subsample from dclm-baseline-1.0, while leaderboard results start with the pools linked above and are processed as described in section 4.
