### ISSUE TITLE
Why are all of these leaderboard empty?

### ISSUE THREAD

**Issue by zhimin-z** [mlfoundations/dclm#5]
Check https://www.datacomp.ai/dclm/leaderboard but found:
<img width="1174" alt="image" src="https://github.com/mlfoundations/dclm/assets/8592144/c5b44186-22ed-42af-bd25-ffc444c5364e">
<img width="1167" alt="image" src="https://github.com/mlfoundations/dclm/assets/8592144/df1bcf60-5d78-495b-843a-5a1eba78d22b">

**Comment by Vaishaal** [comment]
This should be fixed now (we added dclm-baseline), we are working on adding other baselines now.
