### ISSUE TITLE
Release of Trained Models on DCLM-Baseline

### ISSUE THREAD

**Issue by m1k2zoo** [mlfoundations/dclm#50]
Do you plan to release any of the models trained in the paper on your subsets of the DCLM-Pool?

It would be very beneficial for the community if these models were made publicly available (to facilitate studies that aim to analyze the behavior of models trained on DCLM-Baseline).

Thank you for your contributions!

**Comment by afang-story** [comment]
Our currently released models can be found here: https://huggingface.co/collections/apple/dclm-66960ebf2400d314ff19018f
At the moment, we do not have plans to release additional models, but we will make an announcement if this changes.
