### ISSUE TITLE
Local data processing (non-AWS)

### ISSUE THREAD

**Issue by ryoungj** [mlfoundations/dclm#52]
Hi there,

Thank you for your great contributions!

I want to run the 400M-1x setup on a local cluster. I have downloaded the DCLM pool (https://huggingface.co/datasets/mlfoundations/dclm-pool-400m-1x) locally and am trying to run the data processing on a non-AWS local node. Are there any examples, scripts, or instructions that I can refer to for doing this?

Thanks

**Comment by afang-story** [comment]
The data processing workflow is documented in the readme: https://github.com/mlfoundations/dclm?tab=readme-ov-file#processing-the-data

Unfortunately, we did most of our testing reading and writing to s3, so while the commands should be similar, if there are individual portions that do not work locally, you would have to modify the code.
