### ISSUE TITLE
Missing "default_dataset_yaml" for tokenization

### ISSUE THREAD

**Issue by chenweize1998** [mlfoundations/dclm#63]
Hi there. I've encountered an issue where the default `--default_dataset_yaml` file in `ray_processing/tokenize_shuffle.py` is missing. The expected default path for this file is `ray_processing/tokenization_configs/rpj_lm_data.yaml`, but is not included in the repo. 

Would you be able to upload this file to the repository? Alternatively, could you provide an example of what this YAML file should contain? Thanks

**Comment by GeorgiosSmyrnis** [comment]
Hi @chenweize1998 ,

This file is only needed if you do upsampling/downsampling of sources using the `--do_sample` flag - if you don't use the flag then it's not an issue if it doesn't exists.

If you want to do upsampling/downsampling, then this [file](https://github.com/mlfoundations/open_lm/blob/main/open_lm/datapreprocess/metadata/rpj_lm_data.yaml) is an example of the YAML files this parameter expects. The `source` fields have names that appear in the `sampling_frequencies`, the `markers` field is a list of strings that, if found in a filename, the tokenization scripts assumes that the filename corresponds to the respective source. The behavior is that the value for each source in `sampling_frequencies` corresponds to the multiplier to the average number of tokens you will receive from each source.

Let me know if this clarifies things!

**Comment by chenweize1998** [comment]
Thanks!
