### ISSUE TITLE
CommonCrawl WARC files for building mlfoundations/dclm-pool-400m-1x

### ISSUE THREAD

**Issue by Pab1x** [mlfoundations/dclm#64]
Hi. Thanks for your great work.

I'd like to start with CommonCrawl WARC and work on that scale of 400M-1x. However, I do not see a list of WARC files for building mlfoundations/dclm-pool-400m-1x? Can you provide their list please? Or do I need to download all the mlfoundations/dclm-pool-400m-1x to read their isPARTof attributes?

Looking forward to your reply!

**Comment by GeorgiosSmyrnis** [comment]
Hi @Pab1x ,

Thank you for your interest in our work!

Unfortunately we don't have a separate list for the WARC files immediately available. Indeed, you should download the `dclm-pool-400m-1x` data and derive the WARCs from the metadata in each document.
