### ISSUE TITLE
buffer write is so slow

### ISSUE THREAD

**Issue by Yu-Shi** [mlfoundations/dclm#67]
Hello authors,

I’ve noticed that most of the time spent running `ray_processing/tokenize_shuffle.py` is during the buffer write process, while the tokenization itself is relatively fast. Do you have any suggestions for reducing the runtime? I attempted to increase --num_writers_per_node, but it didn’t result in a significant performance improvement.

**Comment by afang-story** [comment]
This is a known issue and the only significant speed up is turning on imbalanced write. You can also try using rust tokenize shuffle on a single node (https://github.com/revbucket/tokshuf-rust).
