### ISSUE TITLE
Missing train_fasttext_classifier.py

### ISSUE THREAD

**Issue by yuzc19** [mlfoundations/dclm#72]
Hi,

I cannot find train_fasttext_classifier.py mentioned in [this file](https://github.com/mlfoundations/dclm/blob/main/baselines/README.md)

Can you provide it in some ways?

Thank you!

**Comment by Mivg** [comment]
HI @yuzc19 ,
Thank you for pointing that out. It should be there now, can you please confirm?

Thanks

**Comment by yuzc19** [comment]
Yes. It works well. Thank you!
