### ISSUE TITLE
How do we just download the data necessary to enter competition?

### ISSUE THREAD

**Issue by davidbrandfonbrener** [mlfoundations/dclm#76]
Thanks for setting up this competition!

The documentation is a bit unclear on how to just download the pool for a single scale for the filtering track. Unfortunately, I don't have 40TB free to download the whole dataset stored here: https://data.commoncrawl.org/contrib/datacomp/index.html. 

Is there an easy way to download just the 137B tokens needed for the 400m scale? 

It's possible I just missed something, but this does seem to be in the readme anywhere. Thanks again!

**Comment by Mivg** [comment]
Hi @davidbrandfonbrener ,
The pools for the individual tracks are hosted on HuggingFace and are availablefor download. 
The one you are looking for is here https://huggingface.co/datasets/mlfoundations/dclm-pool-400m-1x

**Comment by davidbrandfonbrener** [comment]
Oh, nice, thanks! 

I don’t think this is mentioned anywhere in the readme, the competition website, or the paper. It would be nice to add links to make it easier to find.
