### ISSUE TITLE
Request to DCLM-Pool

### ISSUE THREAD

**Issue by SAI990323** [mlfoundations/dclm#8]
Thank you for your great work! I would like to inquire about the process of obtaining access to the DCLM-Pool (I have already submitted the application form but haven't received any feedback) and also, will your DCLM-base dataset be made publicly available and how to access?

**Comment by richardaecn** [comment]
Awesome work! 
Same question here. I requested access to DCLM-pool but haven't got a reply yet. 
The DCLM-Baseline subset looks particularly useful for people to start with. I am wondering how I can get access to DCLM-Baseline. Thanks again for the great work!

**Comment by beccabai** [comment]
Same question, we submitted a request last week but got no reply. Hope to get access to this great dataset.

**Comment by Vaishaal** [comment]
It is in progress! So sorry for the delay. We are currently coordinating with HuggingFace on the release.

**Comment by beccabai** [comment]
I  received your letter.
