### ISSUE TITLE
Reproducing experiments in the paper

### ISSUE THREAD

**Issue by normster** [mlfoundations/dclm#85]
Hi,

I read through the repo and other issues but still am not quite sure how to reproduce the experiments in the paper. Specifically, I'm interested in the official baselines: 400m_1x, 1b_1x, 7b_1x. Is there a version of the data used in these experiments that I can download directly? I saw that there is an s3 bucket called `DCLM-baseline` but this contains over 6TB of data which is much more than what was used in any of the experiments. Do I have to download + process all of this even if I'm only trying to run the 8B token training run with 400m_1x?

Thanks!

**Comment by afang-story** [comment]
We just updated our readme: see https://github.com/mlfoundations/dclm?tab=readme-ov-file#datasets

This section contains huggingface links for the smaller pools. You can go through the various filtering steps starting from these pools to reproduce the baseline experiments.

The DCLM-baseline data was used to train a 7B model for trillions of tokens, and there are a few discrepancies between how this was created when compared to the baselines for the smaller pools. If you want to use this already filtered data, you can also choose to download a random subset of these files to train models with less compute.

**Comment by normster** [comment]
Thank you for the clarification!
