### ISSUE TITLE
Using Evaluation Prompts to Inform Data Selection

### ISSUE THREAD

**Issue by arnavmdas** [mlfoundations/dclm#86]
In the DataComp paper (original one for VLM's), some of the heuristics were based on features from the datasets that were used for evaluations. Is this permitted in the filtering track for DCLM? For example, are we allowed to use featurized MMLU prompts in our selection algorithm?

**Comment by afang-story** [comment]
This is allowed. But if you choose to do so, we would recommend doing additional decontamination checks similar to what is in the paper.
