### ISSUE TITLE
How to download pools for smaller scale tracks

### ISSUE THREAD

**Issue by arnavmdas** [mlfoundations/dclm#87]
On the website (https://data.commoncrawl.org/contrib/datacomp/index.html) only the full 280TB pool is available. Furthermore, https://github.com/mlfoundations/dclm/tree/main/exp_data/datasets/ has several json files but it is not clear which subset corresponds to the smaller tracks.

Where can I find the smaller scale pools for the filtering track?

Thanks you for the great work!

**Comment by afang-story** [comment]
We just updated our readme: see https://github.com/mlfoundations/dclm?tab=readme-ov-file#datasets

This section contains huggingface links for the smaller pools.
