### ISSUE TITLE
How can I calculate expected-ngram-count?

### ISSUE THREAD

**Issue by ethany21** [mlfoundations/dclm#90]
When I run bff to deduplicate text dataset like

```
cargo run --release bff \
   --inputs /data/inputs \
   --output-directory /data/outputs \
   --expected-ngram-count <EXPECTED NGRAM COUNT> \
   --fp-rate 0.01 \
   --min-ngram-size 13 \
   --max-ngram-size 13 \
   --filtering-threshold 0.8 \
   --remove-type naive-both

```

How should I set my EXPECTED NGRAM COUNT?
Do I have to calculate total ngram count from text datasets in my input directory?

For example, if my text datasets contain 100 documents 
and number of words that appear when all text is splited with blank spaces is like 1000000,
does EXPECTED NGRAM COUNT should become 76923 (1000000 / 13)?

Just want to know proper formula to get expected-ngram-count

**Comment by revbucket** [comment]
Hi,

So the expected ngram count should be upper bounded by total number of words in your corpus. In your specific question, then, this would be 1000000. (If you were doing document-level dedup only, this would be #tokens - ngram_size*#documents; for paragraphs this would be #tokens - ngram_size*#paragraphs).

But all that really matters here is that you overshoot expected tokens by a little bit to make sure the false positive rate guarantees are met. To calculate ngrams, you can either extrapolate by counting words on a few documents and then scaling up, or using `wimbd stat` from this package here: https://github.com/allenai/wimbd

Also note, there's been a snafu with the documentation regarding the `--remove-type` flag (see this PR: https://github.com/mlfoundations/dclm/pull/84). To emulate the results from the paper you want to use `--remove-type old-both`.
