### ISSUE TITLE
Understanding the pool sizes at each scale and the DCLM baseline

### ISSUE THREAD

**Issue by ameyagodbole** [mlfoundations/dclm#91]
I need a small clarification on how pool sizes work. My understanding is that:
- The [DCLM-baseline](https://huggingface.co/datasets/mlfoundations/dclm-baseline-1.0) is a 4T token random subset of the full [DCLM-Pool](https://data.commoncrawl.org/contrib/datacomp/DCLM-pool/index.html)
- Each DCLM-pool-*s* for a scale *s* is also a random subset of the full DCLM-pool. The size of the random sample is decided by the competition criterion for that scale (Table 1)
- In Figure 1, the trend line for `DCLM-Baseline` and all experiments where the dataset is called `DCLM-Basline`: the dataset is a random sample of [DCLM-Baseline](https://huggingface.co/datasets/mlfoundations/dclm-baseline-1.0) (and not DCLM-pool-*s* or DCLM-Pool) down-sampled to match the competition criterion.
- All experiments that randomly down-sample the pool are subject to some variance, but results correspond to one sampled subset of the pool.

Is this correct? Am I missing something?

Thanks a lot for putting together all the infrastructure!

**Comment by afang-story** [comment]
1. DCLM-baseline is not a random subset of the DCLM-pool. It is a subset constructed with specific filtering steps (see paper).
2. Each pool for a scale is a random subset of the full DCLM-pool.
3. See point 1.
4. Training experiments are subject to some variance. But as mentioned in point 1, DCLM-baseline is a specifically filtered subset, not a random subset.

**Comment by ameyagodbole** [comment]
Hi. Thank you for the clarifications. A few follow-ups.

1. Sorry for my typo. Yes, I meant to ask if DCLM-Baseline was a filtered subset of DCLM-Pool. Thanks for the clarification.
---
3.  Which of the following or neither is true? Basically, I am wondering is taking a random subset of 8.2B tokens from `DCLM-baseline` is a valid submission for the `400M-1x` scale or should we first apply the DCLM filtering to `DCLM-Pool 400M-1x`.
    - `DCLM-Pool` --(DCLM Filtering)--> `DCLM-Baseline`  --(random subset of 8.2B tokens)--> `DCLM-Baseline 400M-1x` for Fig 1
    - `DCLM-Pool` --(random subset)--> `DCLM-Pool 400M-1x` --(DCLM Filtering)--> `DCLM-Baseline from 400M-1x`  --(random subset of 8.2B tokens)--> `DCLM-Baseline 400M-1x` for Fig 1

**Comment by afang-story** [comment]
Taking random subsets of DCLM-baseline would not be a valid submission, as the submission should correspond to the files in the DCLM pools.

To make things easier, we will soon also give another option for each scale if participants want to start from DCLM-RW.

**Comment by ameyagodbole** [comment]
Thanks for the clarification!
